### ISSUE TITLE
Build failure: The required namespace "eui.provider" is not available

### ISSUE THREAD

**Issue by luminecs** [elastic/eui-cljs#38]
Hello, I encountered such a problem when starting eui-cljs/examples/sample-app, and Opening the `http://localhost:3333/` doesn't show anything(GET http://localhost:3333/js/main.js net::ERR_ABORTED 404 (Not Found)), can you help me? I am new to clojure.  thanks

```
deps  co.elastic/eui-cljs {:mvn/version "41.2.0"}

$ yarn start
yarn run v1.22.19
$ shadow-cljs watch app
shadow-cljs - config: /my-path/eui-cljs/examples/sample-app/shadow-cljs.edn
shadow-cljs - starting via "clojure"
shadow-cljs - HTTP server available at http://localhost:3333
shadow-cljs - server version: 2.15.6 running at http://localhost:9630
shadow-cljs - nREPL server started on port 43659
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[2022-11-14 21:46:39.092 - INFO] :shadow.build.npm/js-invalid-requires - {:resource-name "node_modules/@elastic/eui/lib/components/icon/icon.js", :requires [{:line 599, :column 39}]}
[:app] Build failure:
The required namespace "eui.provider" is not available, it was required by "sample_app/core.cljs".
```

```
deps  co.elastic/eui-cljs {:mvn/version "64.0.0"}

$ yarn start
yarn run v1.22.19
$ shadow-cljs watch app
shadow-cljs - config: /my-path/eui-cljs/examples/sample-app/shadow-cljs.edn
shadow-cljs - starting via "clojure"
NPM dependency "@elastic/eui" has installed version "41.2.0"
"64.0.0" was required by jar:file:/my-path/.m2/repository/co/elastic/eui-cljs/64.0.0/eui-cljs-64.0.0.jar!/deps.cljs
shadow-cljs - HTTP server available at http://localhost:3333
shadow-cljs - server version: 2.15.6 running at http://localhost:9630
shadow-cljs - nREPL server started on port 46599
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[2022-11-14 21:53:26.238 - INFO] :shadow.build.npm/js-invalid-requires - {:resource-name "node_modules/@elastic/eui/lib/components/icon/icon.js", :requires [{:line 599, :column 39}]}
[:app] Build failure:
The required namespace "eui.page-content" is not available, it was required by "sample_app/core.cljs".
```

**Comment by vloth** [comment]
I think the libraries in the example are just outdated.

I updated the `package.json`
```diff
- "@elastic/eui": "41.2.0",
+ "@elastic/eui": "64.0.0",
+ "@emotion/css": "^11.10.5",
+ "@emotion/react": "^11.10.5",
```

The `deps.edn` should be updated too
```diff
- co.elastic/eui-cljs {:mvn/version "41.2.0"}
+ co.elastic/eui-cljs {:mvn/version "64.0.0"}
```

Finally, update the code to reflect the new components. 
[Page template is now deprecated and shouldn't be used](https://github.com/elastic/eui/pull/6194).

`src/sample_app/core.cljs`
```diff
(ns sample-app.core
  (:require  ...
-            [eui.page-content :refer [EuiPageContent]]
-            [eui.page-content-body :refer [EuiPageContentBody]]
+            [eui.page-template :refer [EuiPageTemplate]]
+            [eui.page-section :refer [EuiPageSection]]
...
-       [:> EuiPageContent
-        [:> EuiPageContentBody
+       [:> EuiPageTemplate
+        [:> EuiPageSection
...
```
Your build should be green now ✅.
@haywoood if these changes looks good, I can raise a PR if helps?

**Comment by luminecs** [comment]
@vloth This did solve the problem, thank you very much!!!

**Comment by haywoood** [comment]
> I think the libraries in the example are just outdated.
> 
> I updated the `package.json`
> 
> ```diff
> - "@elastic/eui": "41.2.0",
> + "@elastic/eui": "64.0.0",
> + "@emotion/css": "^11.10.5",
> + "@emotion/react": "^11.10.5",
> ```
> 
> The `deps.edn` should be updated too
> 
> ```diff
> - co.elastic/eui-cljs {:mvn/version "41.2.0"}
> + co.elastic/eui-cljs {:mvn/version "64.0.0"}
> ```
> 
> Finally, update the code to reflect the new components. [Page template is now deprecated and shouldn't be used](https://github.com/elastic/eui/pull/6194).
> 
> `src/sample_app/core.cljs`
> 
> ```diff
> (ns sample-app.core
>   (:require  ...
> -            [eui.page-content :refer [EuiPageContent]]
> -            [eui.page-content-body :refer [EuiPageContentBody]]
> +            [eui.page-template :refer [EuiPageTemplate]]
> +            [eui.page-section :refer [EuiPageSection]]
> ...
> -       [:> EuiPageContent
> -        [:> EuiPageContentBody
> +       [:> EuiPageTemplate
> +        [:> EuiPageSection
> ...
> ```
> 
> Your build should be green now ✅. @haywoood if these changes looks good, I can raise a PR if helps?

That would be great thank you!
